routes/web.php
    Route::get('report/{id}/edit', 'ReportController@edit')->name('reports.edit');
    Route::delete('report/delete', 'ReportController@delete')->name('reports.delete');
    Route::put('report/{id}/update', 'ReportController@update')->name('reports.update');
    Route::post('report/create', 'ReportController@create')->name('reports.create');
    Route::put('report/{id}/approve', 'ReportController@approve')->name('reports.approve');

    Route::get('reports/{id}/view', 'ReportController@index')->name('reports.view');

    Route::get('/downloadPDF/{id}','ReportController@downloadPDF');
    // Route::get('export', 'ReportController@export');

    Route::get('/send-email', 'MailController@sendEmail')->name('mail');
    Route::get('sendnotif', 'MailController@sendNotification');
    Route::post('report/{id}/submit', 'ReportController@submitreport')->name('reports.submit');;
    Route::get('/report/{id}/export', 'ReportController@export')->name('reports.export');


    // Route::get('/Dashboard', 'HomeController@index')->name('home');
    Route::get('customers', 'CustomerController@index')->name('customer');
    Route::get('items', 'ItemController@index')->name('item');

    Route::get('applications', 'applicationsController@index')->name('applications');

    Route::get('Search', 'Controller@index')->name('');
    Route::get('Dashboard', 'HomeController@index')->name('home');
    Route::get('AdminPanel', 'AdminPanelController@index')->name('AdminPanel');

    });

         //Invoices Routes

    Route::prefix('invoice')->name('invoice.')->group(function () {

        Route::middleware(['verified', 'auth'])->group(function () {

         Route::get('invoices', 'InvoiceController@index')->name('invoice');
        // Route::get('reports', 'InvoiceController@index')->name('reports');
        Route::get('customers', 'InvoiceCustomerController@index')->name('customer');
        Route::get('items', 'InvoiceController@index')->name('item');


        });
        });


        Route::prefix('docsign')->name('docsign.')->group(function () {

            Route::middleware(['verified', 'auth'])->group(function () {

             Route::get('sign', 'DocsignController@sign')->name('sign');
            Route::get('documents', 'DocsignController@index')->name('document');
            Route::get('templates', 'DocsignController@index')->name('template');
            Route::get('signForms', 'DocsignController@signForm')->name('signinform');
            Route::get('reports', 'DocsignController@index')->name('report');


            });
            });
    Route::prefix('expenses')->name('expenses.')->group(function () {

        Route::middleware(['verified', 'auth'])->group(function () {
        Route::get('expense/view', 'ExpenseController@view')->name('view');
        Route::post('expense/create', 'ExpenseController@create')->name('create');
        Route::get('expense/{id}/edit', 'ExpenseController@edit')->name('edit');
        Route::get('expense/{id}/view', 'ExpenseController@view')->name('view');
        Route::delete('expense/delete', 'ExpenseController@delete')->name('delete');
        Route::put('expense/{id}/update', 'ExpenseController@update')->name('update');

         Route::get('expenses', 'ExpenseController@index')->name('expenses');
        // Route::get('reports', 'InvoiceController@index')->name('reports');
        // Route::get('customers', 'InvoiceCustomerController@index')->name('customer');
        // Route::get('items', 'InvoiceController@index')->name('item');
        });
        });





        Route::prefix('reports')->name('reports.')->group(function () {

            Route::middleware(['verified', 'auth'])->group(function () {
            Route::get('reports/{id}/view', 'ReportController@view')->name('view');
             Route::get('reports', 'ReportController@index')->name('reports');
            // Route::get('documents', 'DocsignController@index')->name('document');
            // Route::get('templates', 'DocsignController@index')->name('template');
            // Route::get('signForms', 'DocsignController@signForm')->name('signinform');
            // Route::get('reports', 'DocsignController@index')->name('report');
            });
            });



    Route::prefix('user-management')->name('user-management.')->group(function () {

        Route::middleware(['verified', 'auth'])->group(function () {

        //Users Routes
        Route::get('users', 'UserController@index')->name('users');

        Route::get('user/my-profile', 'UserController@profile')->name('user.my_profile');
        Route::put('user/{id}/edit_profile', 'UserController@edit_user')->name('user.edit_user');
        Route::get('user/{id}/edit', 'UserController@edit')->name('user.edit');
        Route::delete('user/delete', 'UserController@delete')->name('user.delete');
        Route::put('user/{id}/update', 'UserController@update')->name('user.update');
        Route::post('user/create', 'UserController@create')->name('user.create');

        //Permissions Routes
        Route::get('permissions', 'PermissionsController@index')->name('permissions');
        Route::post('permissions/create', 'PermissionsController@create')->name('permissions.create');

        Route::get('permissions/{id}/edit', 'PermissionsController@edit')->name('permissions.edit');
        Route::put('permissions/{id}/update', 'PermissionsController@update')->name('permissions.update');
        Route::delete('permissions/delete', 'PermissionsController@delete')->name('permissions.delete');

        //Roles Routes
        Route::get('roles', 'RolesController@index')->name('roles');
        Route::post('roles/create', 'RolesController@create')->name('roles.create');
        Route::get('roles/{id}/edit', 'RolesController@edit')->name('roles.edit');
        Route::get('role/{id}/view', 'RolesController@view')->name('roles.view');
        Route::delete('role/delete', 'RolesController@delete')->name('roles.delete');

        Route::get('roles/newFormView', 'RolesController@emptyForm')->name('roles.emptyForm');
        Route::put('roles/{id}/update', 'RolesController@update')->name('roles.update');

      //categories Routes
      Route::get('categories', 'categoriesController@index')->name('categories');
      Route::post('categories/create', 'CategoriesController@create')->name('categories.create');
    Route::get('categories/view', 'CategoriesController@view')->name('categories.view');
      Route::get('categories/{id}/edit', 'CategoriesController@edit')->name('categories.edit');
      Route::put('categories/{id}/update', 'CategoriesController@update')->name('categories.update');
      Route::delete('categories/delete', 'CategoriesController@delete')->name('categories.delete');


      //merchants
      Route::get('merchants', 'MerchantsController@index')->name('merchants');
      Route::post('merchants/create', 'MerchantsController@create')->name('merchants.create');
      Route::get('merchants/{id}/view', 'MerchantsController@view')->name('merchants.view');
      Route::get('merchants/{id}/edit', 'MerchantsController@edit')->name('merchants.edit');
      Route::put('merchants/{id}/update', 'MerchantsController@update')->name('merchants.update');
      Route::delete('merchants/delete', 'MerchantsController@delete')->name('merchants.delete');

      //customers
      Route::get('customers', 'CustomersController@index')->name('customers');
      Route::post('customers/create', 'CustomersController@create')->name('customers.create');
      Route::get('customers/{id}/view', 'CustomersController@view')->name('customers.view');

      Route::get('customers/{id}/edit', 'CustomersController@edit')->name('customers.edit');
      Route::put('customers/{id}/update', 'CustomersController@update')->name('customers.update');
      Route::delete('customers/delete', 'CustomersController@delete')->name('customers.delete');


//currencies

Route::get('currencies', 'currenciesController@index')->name('currencies');
Route::post('currencies/create', 'currenciesController@create')->name('currencies.create');
Route::post('currencies/view', 'currenciesController@view')->name('currencies.view');

Route::get('currencies/{id}/edit', 'currenciesController@edit')->name('currencies.edit');
Route::put('currencies/{id}/update', 'currenciesController@update')->name('currencies.update');
Route::delete('currencies/delete', 'currenciesController@delete')->name('currencies.delete');



Route::get('paidthrough', 'PaidthroughController@index')->name('paidthrough');
Route::post('paidthrough/create', 'PaidthroughController@create')->name('paidthrough.create');
Route::post('paidthrough/view', 'PaidthroughController@view')->name('paidthrough.view');

Route::get('paidthrough/{id}/edit', 'PaidthroughController@edit')->name('paidthrough.edit');
Route::put('paidthrough/{id}/update', 'PaidthroughController@update')->name('paidthrough.update');
Route::delete('paidthrough/delete', 'PaidthroughController@delete')->name('paidthrough.delete');


Route::get('accounttype', 'AccounttypeController@index')->name('accounttype');
Route::post('accounttype/create', 'AccounttypeController@create')->name('accounttype.create');
Route::get('accounttype/{id}/view', 'AccounttypeController@view')->name('accounttype.view');

Route::get('accounttype/{id}/edit', 'AccounttypeController@edit')->name('accounttype.edit');
Route::put('accounttype/{id}/update', 'AccounttypeController@update')->name('accounttype.update');
Route::delete('accounttype/delete', 'AccounttypeController@delete')->name('accounttype.delete');

        });
        });

Route::get('test',function(){

// $expenses=\App\Expense::with('reports')->get();
// $reports=\App\Report::with('expenses')->get();

// $expense=\App\Expense::create([
//      =>
// ]);
// categories
// $expense=\App\Expense::find(1);
// dd($expense->reports);

// $reports=\App\Report::all();
// dd($report->expenses);

// $report=\App\Report::find(1);

// $u=$report->expenses()->attach([2,3]);
// dd($u);

app/Permission.php
<?php

namespace App;

use Laratrust\Models\LaratrustPermission;

class Permission extends LaratrustPermission
{
    public $guarded = [];
}

app/Http/Controllers/PermissionsController.php
<?php

namespace App\Http\Controllers;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Mail;
use App\Mail\MailNotify;

use App\Classes\ToastNotification;
use App\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Validation\ValidationException;

class PermissionsController extends Controller {
	//
	public function __construct() {
		$this->middleware('auth');
	}

	public function index() {
		$permissions = Permission::all();
		return view('layouts.permissions.index', compact('permissions'));
	}

	public function create(Request $request) {



			$this->validate($request, [
				'name' => 'bail|required|unique:permissions,name|string|min:5',
				'display_name' => 'required|string|min:5',
				'description' => 'required|string|min:5',
			]);



		try {
			$createPermission = new Permission();
			$createPermission->name = str_slug(strtolower($request->name));
			$createPermission->display_name = $request->display_name;
			$createPermission->description = $request->description;
			$createPermission->save();

            $request->session()->flash('status', [
                'error' => false,
                'title' => 'Great!',
                'message' => 'Role Updated!',
            ]);
//            notify(new ToastNotification('Successful!', 'Permission Added!', 'success'));
		} catch (\Illuminate\Database\QueryException $ex) {
//            notify(new ToastNotification('Error!', 'Permission name already exist or check enter appropriate data.!', 'warning'));
			return back();
		}

		return back();
	}

	public function edit($id) {
		$permission_id = Crypt::decrypt($id);
		$permission = Permission::find($permission_id);
		return view('layouts.permissions.edit', compact('permission'));
	}

	public function update(Request $request,$id) {

		$pid = Crypt::decrypt($id);

			$this->validate($request, [
				'name' => 'required|unique:permissions,name,' . $pid . '|string|min:3',
				'display_name' => 'required|string|min:3',
				'description' => 'required|string|min:3',
			]);

//dd("hello");
		try {
			$updatePermission = Permission::find($pid);
			$updatePermission->name = str_slug(strtolower($request->name));
			$updatePermission->display_name = $request->display_name;
			$updatePermission->description = $request->description;
			$updatePermission->save();
//			    notify(new ToastNotification('Successful!', 'Permission updated!', 'success'));

		} catch (\Illuminate\Database\QueryException $ex) {
			notify(new ToastNotification('Error!', 'Permission name already exist or check enter appropriate data.!', 'warning'));
			return back();
		}
	return	redirect()->route('user-management.permissions');
	}

	public function delete(Request $request) {
		$id = Crypt::decrypt($request->input('id'));
		// dd($id);
		$permission = Permission::where('id', $id)->first();

		if (empty($permission)) {
			$request->session()->flash('status', [
				'error' => true,
				'title' => 'Sorry!',
				'message' => 'Issue deleting permission, please retry.',
			]);
		}

		if ($permission->delete()) {
			$request->session()->flash('status', [
				'error' => false,
				'title' => 'Deleted!',
				'message' => 'permission deleted successfully.',
			]);
		}

		return redirect()->route('user-management.permissions');
	}

}

resources/views/layouts/permissions/edit.blade.php
@extends('layouts.app')

@section('content')
    <main class="main">
        <!-- Breadcrumb-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item">
                <a href="#">Admin</a>
            </li>
            <li class="breadcrumb-item active">Permissions</li>
        </ol>
        <div class="container-fluid">

            <div class="ui-view">
                <div class="row">

                    <!-- /.col-->
                    <div class=" col-sm-12 col-md-12 accordion" id="accordion">

                        <div class="card">
                            <div class="card-header" id="headingOne">
                                <i class="icon-note"></i>Edit Permissions
                                <div class="card-header-actions">
                                    <a class="card-header-action" href="#" target="_blank"  data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    </a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h6>Simple Form</h6>
                                        <form id="permissionForm"   method="POST" action="{{ route('user-management.permissions.update',[\Illuminate\Support\Facades\Crypt::encrypt($permission->id)]) }}">
                                            @csrf {{method_field('PUT')}}
                                        {{--<input  type="hidden" name="id"  value="{{\Illuminate\Support\Facades\Crypt::encrypt($permission->id)}}">--}}
                                            <div class="form-group">
                                                <label class="col-form-label" for="name">Name</label>
                                                <input class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" type="text" name="name" value="{{ old('name')?old('name'):$permission->name }}" placeholder=" name" />
                                                @if ($errors->has('name'))
                                                    <p class="text-right mb-0">
                                                        <small class="warning text-muted">{{ $errors->first('name') }}</small>
                                                    </p>
                                                @endif
                                            </div>
                                            <div class="form-group">
                                                <label class="col-form-label" for="display_name">Display Name</label>
                                                <input class="form-control {{ $errors->has('display_name') ? ' is-invalid' : '' }}" id="display_name" type="text" name="display_name" value="{{ old('display_name')?old('display_name'):$permission->display_name }}" placeholder="Display name" />
                                                @if ($errors->has('display_name'))
                                                    <p class="text-right mb-0">
                                                        <small class="warning text-muted">{{ $errors->first('display_name') }}</small>
                                                    </p>
                                                @endif
                                            </div>
                                            <div class="form-group">
                                                <label class="col-form-label" for="username">Description</label>
                                                <input class="form-control {{ $errors->has('description') ? ' is-invalid' : '' }}" id="description" type="text" name="description" value="{{ old('description')?old('description'):$permission->description }}" placeholder="description" />
                                                @if ($errors->has('description'))
                                                    <p class="text-right mb-0">
                                                        <small class="warning text-muted">{{ $errors->first('description') }}</small>
                                                    </p>
                                                @endif
                                            </div>
                                            <div class="form-group">
                                                <button class="btn btn-primary" type="submit" name="save" value="save">Save</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.col-->
                </div>
                <!-- /.row-->



            </div>

        </div>

    </main>

@endsection

resources/views/layouts/permissions/index.blade.php
@extends('layouts.app')

@section('content')
  {{-- <div class="container">
      <div class="row justify-content-center">
          <div class="col-md-8">
              <div class="card">
                  <div class="card-header">Dashboard</div>


                  <div class="card-body">
                      @if (session('status'))
                          <div class="alert alert-success" role="alert">
                              {{ session('status') }}
                          </div>
                      @endif

                      You are logged in!
                  </div>
              </div>
          </div>
      </div>


  </div>
   --}}

        <main class="main">
      <!-- Breadcrumb-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">
          <a href="#">Admin</a>
        </li>
        <li class="breadcrumb-item active">Permissions</li>
      </ol>
      <div class="container-fluid">

        <div class="ui-view">
          <div class="row">


            <!-- /.col-->
            <div class=" col-sm-12 col-md-12 accordion" id="accordion">

              <div class="card">
                <div class="card-header" id="headingOne">
                  <i class="icon-note"></i>Add Permissions
                  <div class="card-header-actions">
                    <a class="card-header-action" href="#" target="_blank"  data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    </a>
                  </div>
                </div>

                <div class="card-body">

                  <div class="row">
                    <div class="col-md-12">
                      <h6>Simple Form</h6>
                      {{--@if (session('status'))--}}
                        {{--<div class="alert alert-success">--}}
                          {{--{{ session('status') }}--}}
                        {{--</div>--}}
                      {{--@endif--}}

                      @if (session('status'))
                        <div class="alert alert-success" role="alert">
                          {{ session('status') }}
                        </div>
                      @endif
                      <form id="permissionForm"   method="POST" action="{{ route('user-management.permissions.create')}}">
                        @csrf

                        <div class="form-group">
                          <label class="col-form-label" for="name">Name</label>
                          <input class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" type="text" name="name" value="" placeholder=" name" />
                          @if ($errors->has('name'))
                            <p class="text-right mb-0">
                              <small class="warning text-muted">{{ $errors->first('name') }}</small>
                            </p>
                          @endif

                        </div>
                        <div class="form-group">
                          <label class="col-form-label" for="display_name">Display Name</label>
                          <input class="form-control {{ $errors->has('display_name') ? ' is-invalid' : '' }}" id="display_name" type="text" name="display_name" value="" placeholder="Display name" />
                          @if ($errors->has('display_name'))
                            <p class="text-right mb-0">
                              <small class="warning text-muted">{{ $errors->first('display_name') }}</small>
                            </p>
                          @endif
                        </div>
                        <div class="form-group">
                          <label class="col-form-label" for="username">Description</label>
                          <input class="form-control {{ $errors->has('description') ? ' is-invalid' : '' }}" id="description" type="text" name="description" value="" placeholder="description" />
                          @if ($errors->has('description'))
                            <p class="text-right mb-0">
                              <small class="warning text-muted">{{ $errors->first('description') }}</small>
                            </p>
                          @endif
                        </div>

                        <div class="form-group">
                          <button class="btn btn-primary" type="submit" name="save" value="save">Save</button>
                        </div>

                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.col-->
          </div>
          <!-- /.row-->

          <div class="animated fadeIn">
            <div class="card">
              <div class="card-header">
                <i class="fa fa-edit"></i> List Permissions
                <div class="card-header-actions">

                </div>
              </div>
              <div class="card-body">
                <table class="table table-striped table-bordered datatable">
                  <thead>
                  <tr>
                    <th>Name</th>
                    <th>Display Name</th>
                    <th>Description</th>
                    {{-- <th>Permissions</th> --}}
                    <th>Actions</th>
                  </tr>
                  </thead>
                  <tbody>
                  @if($permissions->count() > 0)
                    @foreach($permissions as $permission)
                  <tr>
                    <td>{{$permission->name}}</td>
                    <td>{{$permission->display_name}}</td>
                    <td>{{$permission->description}}</td>

                    <td>
                      <a class="btn btn-success" href="#">
                       view <i class="fa fa-search-plus"></i>
                      </a>
                      <a class="btn btn-info" href="{{route('user-management.permissions.edit',[\Illuminate\Support\Facades\Crypt::encrypt($permission->id)])}}">
                       edit <i class="fa fa-edit"></i>
                      </a>
                      {{--<a class="btn btn-danger" href="{{route('user-management.permissions.delete',[\Illuminate\Support\Facades\Crypt::encrypt($permission->id)])}}">--}}
                        {{--<i class="fa fa-trash-o">--}}
                        {{--</i>--}}
                      {{--</a>--}}

                      <a class="btn btn-danger" href="#" onclick="deletePermission('{{$permission->id}}')">
                       delete <i class="fa fa-search-plus"></i>
                      </a>

                      {{--<input style="" class="jsgrid-button jsgrid-delete-button"--}}
                             {{--type="button"--}}
                             {{--title="Delete" onclick="deletePermission('{{$permission->id}}')">--}}

                      <form id="delete-form{{$permission->id}}"
                            action="{{ route('user-management.permissions.delete') }}" method="POST" style="display: none;">
                        @csrf
                        @method('DELETE')

                        <input type="hidden" name="id"
                               value="{{\Illuminate\Support\Facades\Crypt::encrypt($permission->id)}}">
                      </form>

                    </td>
                  </tr>
                    @endforeach
                  @else
                    <tr>
                      <td colspan="4" class="text-center">No Permission Set</td>
                    </tr>
                  @endif
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>

</div>

    </main>

@endsection
<script>
    function deletePermission(key) {


        if (confirm('Are you sure, you want to delete this property?')) {
            event.preventDefault();
            document.getElementById('delete-form' + key).submit();
        } else {
            event.preventDefault();
            document.getElementById('delete-form' + key).reset();
        }




    }



                                </script>