routes/web.php
    Route::get('report/{id}/edit', 'ReportController@edit')->name('reports.edit');
    Route::delete('report/delete', 'ReportController@delete')->name('reports.delete');
    Route::put('report/{id}/update', 'ReportController@update')->name('reports.update');
    Route::post('report/create', 'ReportController@create')->name('reports.create');
    Route::put('report/{id}/approve', 'ReportController@approve')->name('reports.approve');

    Route::get('reports/{id}/view', 'ReportController@index')->name('reports.view');

    Route::get('/downloadPDF/{id}','ReportController@downloadPDF');
    // Route::get('export', 'ReportController@export');

    Route::get('/send-email', 'MailController@sendEmail')->name('mail');
    Route::get('sendnotif', 'MailController@sendNotification');
    Route::post('report/{id}/submit', 'ReportController@submitreport')->name('reports.submit');;
    Route::get('/report/{id}/export', 'ReportController@export')->name('reports.export');


    // Route::get('/Dashboard', 'HomeController@index')->name('home');
    Route::get('customers', 'CustomerController@index')->name('customer');
    Route::get('items', 'ItemController@index')->name('item');

    Route::get('applications', 'applicationsController@index')->name('applications');

    Route::get('Search', 'Controller@index')->name('');
    Route::get('Dashboard', 'HomeController@index')->name('home');
    Route::get('AdminPanel', 'AdminPanelController@index')->name('AdminPanel');

    });

         //Invoices Routes

    Route::prefix('invoice')->name('invoice.')->group(function () {

        Route::middleware(['verified', 'auth'])->group(function () {

         Route::get('invoices', 'InvoiceController@index')->name('invoice');
        // Route::get('reports', 'InvoiceController@index')->name('reports');
        Route::get('customers', 'InvoiceCustomerController@index')->name('customer');
        Route::get('items', 'InvoiceController@index')->name('item');


        });
        });


        Route::prefix('docsign')->name('docsign.')->group(function () {

            Route::middleware(['verified', 'auth'])->group(function () {

             Route::get('sign', 'DocsignController@sign')->name('sign');
            Route::get('documents', 'DocsignController@index')->name('document');
            Route::get('templates', 'DocsignController@index')->name('template');
            Route::get('signForms', 'DocsignController@signForm')->name('signinform');
            Route::get('reports', 'DocsignController@index')->name('report');


            });
            });
    Route::prefix('expenses')->name('expenses.')->group(function () {

        Route::middleware(['verified', 'auth'])->group(function () {
        Route::get('expense/view', 'ExpenseController@view')->name('view');
        Route::post('expense/create', 'ExpenseController@create')->name('create');
        Route::get('expense/{id}/edit', 'ExpenseController@edit')->name('edit');
        Route::get('expense/{id}/view', 'ExpenseController@view')->name('view');
        Route::delete('expense/delete', 'ExpenseController@delete')->name('delete');
        Route::put('expense/{id}/update', 'ExpenseController@update')->name('update');

         Route::get('expenses', 'ExpenseController@index')->name('expenses');
        // Route::get('reports', 'InvoiceController@index')->name('reports');
        // Route::get('customers', 'InvoiceCustomerController@index')->name('customer');
        // Route::get('items', 'InvoiceController@index')->name('item');
        });
        });





        Route::prefix('reports')->name('reports.')->group(function () {

            Route::middleware(['verified', 'auth'])->group(function () {
            Route::get('reports/{id}/view', 'ReportController@view')->name('view');
             Route::get('reports', 'ReportController@index')->name('reports');
            // Route::get('documents', 'DocsignController@index')->name('document');
            // Route::get('templates', 'DocsignController@index')->name('template');
            // Route::get('signForms', 'DocsignController@signForm')->name('signinform');
            // Route::get('reports', 'DocsignController@index')->name('report');
            });
            });



    Route::prefix('user-management')->name('user-management.')->group(function () {

        Route::middleware(['verified', 'auth'])->group(function () {

        //Users Routes
        Route::get('users', 'UserController@index')->name('users');

        Route::get('user/my-profile', 'UserController@profile')->name('user.my_profile');
        Route::put('user/{id}/edit_profile', 'UserController@edit_user')->name('user.edit_user');
        Route::get('user/{id}/edit', 'UserController@edit')->name('user.edit');
        Route::delete('user/delete', 'UserController@delete')->name('user.delete');
        Route::put('user/{id}/update', 'UserController@update')->name('user.update');
        Route::post('user/create', 'UserController@create')->name('user.create');

        //Permissions Routes
        Route::get('permissions', 'PermissionsController@index')->name('permissions');
        Route::post('permissions/create', 'PermissionsController@create')->name('permissions.create');

        Route::get('permissions/{id}/edit', 'PermissionsController@edit')->name('permissions.edit');
        Route::put('permissions/{id}/update', 'PermissionsController@update')->name('permissions.update');
        Route::delete('permissions/delete', 'PermissionsController@delete')->name('permissions.delete');

        //Roles Routes
        Route::get('roles', 'RolesController@index')->name('roles');
        Route::post('roles/create', 'RolesController@create')->name('roles.create');
        Route::get('roles/{id}/edit', 'RolesController@edit')->name('roles.edit');
        Route::get('role/{id}/view', 'RolesController@view')->name('roles.view');
        Route::delete('role/delete', 'RolesController@delete')->name('roles.delete');

        Route::get('roles/newFormView', 'RolesController@emptyForm')->name('roles.emptyForm');
        Route::put('roles/{id}/update', 'RolesController@update')->name('roles.update');

      //categories Routes
      Route::get('categories', 'categoriesController@index')->name('categories');
      Route::post('categories/create', 'CategoriesController@create')->name('categories.create');
    Route::get('categories/view', 'CategoriesController@view')->name('categories.view');
      Route::get('categories/{id}/edit', 'CategoriesController@edit')->name('categories.edit');
      Route::put('categories/{id}/update', 'CategoriesController@update')->name('categories.update');
      Route::delete('categories/delete', 'CategoriesController@delete')->name('categories.delete');


      //merchants
      Route::get('merchants', 'MerchantsController@index')->name('merchants');
      Route::post('merchants/create', 'MerchantsController@create')->name('merchants.create');
      Route::get('merchants/{id}/view', 'MerchantsController@view')->name('merchants.view');
      Route::get('merchants/{id}/edit', 'MerchantsController@edit')->name('merchants.edit');
      Route::put('merchants/{id}/update', 'MerchantsController@update')->name('merchants.update');
      Route::delete('merchants/delete', 'MerchantsController@delete')->name('merchants.delete');

      //customers
      Route::get('customers', 'CustomersController@index')->name('customers');
      Route::post('customers/create', 'CustomersController@create')->name('customers.create');
      Route::get('customers/{id}/view', 'CustomersController@view')->name('customers.view');

      Route::get('customers/{id}/edit', 'CustomersController@edit')->name('customers.edit');
      Route::put('customers/{id}/update', 'CustomersController@update')->name('customers.update');
      Route::delete('customers/delete', 'CustomersController@delete')->name('customers.delete');


//currencies

Route::get('currencies', 'currenciesController@index')->name('currencies');
Route::post('currencies/create', 'currenciesController@create')->name('currencies.create');
Route::post('currencies/view', 'currenciesController@view')->name('currencies.view');

Route::get('currencies/{id}/edit', 'currenciesController@edit')->name('currencies.edit');
Route::put('currencies/{id}/update', 'currenciesController@update')->name('currencies.update');
Route::delete('currencies/delete', 'currenciesController@delete')->name('currencies.delete');



Route::get('paidthrough', 'PaidthroughController@index')->name('paidthrough');
Route::post('paidthrough/create', 'PaidthroughController@create')->name('paidthrough.create');
Route::post('paidthrough/view', 'PaidthroughController@view')->name('paidthrough.view');

Route::get('paidthrough/{id}/edit', 'PaidthroughController@edit')->name('paidthrough.edit');
Route::put('paidthrough/{id}/update', 'PaidthroughController@update')->name('paidthrough.update');
Route::delete('paidthrough/delete', 'PaidthroughController@delete')->name('paidthrough.delete');


Route::get('accounttype', 'AccounttypeController@index')->name('accounttype');
Route::post('accounttype/create', 'AccounttypeController@create')->name('accounttype.create');
Route::get('accounttype/{id}/view', 'AccounttypeController@view')->name('accounttype.view');

Route::get('accounttype/{id}/edit', 'AccounttypeController@edit')->name('accounttype.edit');
Route::put('accounttype/{id}/update', 'AccounttypeController@update')->name('accounttype.update');
Route::delete('accounttype/delete', 'AccounttypeController@delete')->name('accounttype.delete');

        });
        });

Route::get('test',function(){

// $expenses=\App\Expense::with('reports')->get();
// $reports=\App\Report::with('expenses')->get();

// $expense=\App\Expense::create([
//      =>
// ]);
// categories
// $expense=\App\Expense::find(1);
// dd($expense->reports);

// $reports=\App\Report::all();
// dd($report->expenses);

// $report=\App\Report::find(1);

// $u=$report->expenses()->attach([2,3]);
// dd($u);

app/Merchant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Merchant extends Model
{
    //

    protected $table = 'merchants';

      /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'code',
    ];



    public function expenses()
    {
        return $this->belongsToMany(Expense::Class);
    }



//     public function expenses()
// {
//     return $this->morphToMany('App\Expense','expendable');
// }


}

app/Http/Controllers/MerchantsController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Auth;
use App\Merchant;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Mail;
use App\Mail\MailNotify;

class MerchantsController extends Controller
{

	public function index() {
        $id = Auth::user();

		 $Merchants=Merchant::all();
  return view('layouts.merchants.index',compact('Merchants'));

    }



//     public function view() {
//         $id = Auth::user();

// 		 $Invoices;
//   return view('layouts.merchants.view');
//     }

    public function view(
        $id
        ) {
		$c_id = Crypt::decrypt($id);

		$category = Category::find($c_id);
// return 0;
        return view('layouts.merchants.view',compact('merchants'));
	}


    public function create(Request $request) {

        $this->validate($request, [
            'name' => 'required|string|min:5',
            'code' => 'required|string|min:1',

        ]);

// dd($request->all());

    // try {
        $createMerchant = new Merchant();
        $createMerchant->name = $request->name;
        $createMerchant->code = $request->code;
        $createMerchant->save();
// dd("hello");

        // $request->session()->flash('status', [
        //     'error' => false,
        //     'title' => 'Great!',
        //     'message' => 'Expense Created!',
        // ]);
//            notify(new ToastNotification('Successful!', ' Expense Created!', 'success'));
    // } catch (\Illuminate\Database\QueryException $ex) {
        // dd("error");
//            notify(new ToastNotification('Error!', 'Expense  already exist or check enter appropriate data.!', 'warning'));
        // return back();
    // }

    return back();
}



public function edit($id) {

    $r_id = Crypt::decrypt($id);

    $merchants = Merchant::find($r_id);

    return view('layouts.merchants.edit',compact('merchants'));

}

public function update(Request $request,$id) {
    		// dd($id);
            $m_id = Crypt::decrypt($id);

            //creates a slug name

            $this->validate($request, [
                'name' => 'required|string|min:3|unique:merchants,name,' . $m_id,
                'code' => 'nullable|string|min:3',
            ]);

            try {
                $owner = Merchant::find($m_id);
                $owner->name = $request->name;
                $owner->code = $request->code;
                $owner->save();

                // $owner->syncPermissions($request->permissions);

                $request->session()->flash('status', [
                    'error' => false,
                    'title' => 'Great!',
                    'message' => 'merchant Updated!',
                ]);

                return redirect()->route('user-management.merchants');


            } catch (QueryException $exception) {

                $request->session()->flash('status', [
                    'error' => true,
                    'title' => 'Sorry!',
                    'message' => 'Issue updating merchant.',
                ]);

                return back();
            }
        }


}

resources/views/layouts/merchants/edit.blade.php
@extends('layouts.app')

@section('content')

    <main class="main">
        <!-- Breadcrumb-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item">
                <a href="#">Admin</a>
            </li>
            <li class="breadcrumb-item active">Roles</li>
        </ol>
        <div class="container-fluid">

            <div class="ui-view">
                <div class="row">

                    <!-- /.col-->
                    <div class=" col-sm-12 col-md-12 accordion" id="accordion">

                        <div class="card">
                            <div class="card-header" id="headingOne">
                                <i class="icon-note"></i>Edit Merchant
                                <div class="card-header-actions">
                                    <a class="card-header-action" href="#" target="_blank"  data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    </a>
                                </div>
                            </div>

                            <div class="card-body">

                                <div class="row">
                                    <div class="col-md-12">
                                        <h6>Simple Form</h6>
                                        <form id="roleForm"   method="POST" action="{{route('user-management.merchants.update',[\Illuminate\Support\Facades\Crypt::encrypt($merchants->id)])}}">
                                            @csrf {{method_field('PUT')}}
                                            {{--<input  type="hidden" name="id"  value="{{\Illuminate\Support\Facades\Crypt::encrypt($merchants->id)}}">--}}

                                            <div class="form-group">
                                                <label class="col-form-label" for="name">Name</label>
                                                <input class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" type="text" name="name" value="{{ old('name')?old('name'):$merchants->name }}" placeholder=" name" />
                                                @if ($errors->has('name'))
                                                    <p class="text-right mb-0">
                                                        <small class="warning text-muted">{{ $errors->first('name') }}</small>
                                                    </p>
                                                @endif

                                            </div>

                                            <div class="form-group">
                                                <label class="col-form-label" for="code">Code</label>
                                                <input class="form-control {{ $errors->has('code') ? ' is-invalid' : '' }}" id="code" type="text" name="code" value="{{ old('code')?old('code'):$merchants->code }}" placeholder="code" />
                                                @if ($errors->has('code'))
                                                    <p class="text-right mb-0">
                                                        <small class="warning text-muted">{{ $errors->first('code') }}</small>
                                                    </p>
                                                @endif
                                            </div>

                                            <div class="form-group">
                                                <button class="btn btn-primary" type="submit" name="save" value="save">Save</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.col-->
                </div>
                <!-- /.row-->

            </div>

        </div>

    </main>

@endsection

resources/views/layouts/merchants/index.blade.php
@extends('layouts.app')

@section('content')

  <main class="main">
    <!-- Breadcrumb-->
    <ol class="breadcrumb">
      <li class="breadcrumb-item">Home</li>
      <li class="breadcrumb-item">
        <a href="#">Admin</a>
      </li>
      <li class="breadcrumb-item active">Merchant</li>
    </ol>
    <div class="container-fluid">
      <div class="ui-view">
        <div class="row">
          <!-- /.col-->
          <div class=" col-sm-12 col-md-12 accordion" id="accordion">
            <div class="card">
              <div class="card-header" id="headingOne">
                <i class="icon-note"></i>Add Merchant
                <div class="card-header-actions">
                  <a class="card-header-action" href="#" target="_blank"  data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                  </a>
                </div>
              </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-md-12">
                    <h6>Simple Form</h6>
                    <form id="InputForm"   method="POST" action="{{ route('user-management.merchants.create')}}">
                      @csrf

                      <div class="form-group">
                        <label class="col-form-label" for="name">name</label>
                        <input class="form-control {{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" type="text" name="name" value="{{ old('name')}}" placeholder=" name" />
                        @if ($errors->has('name'))
                          <p class="text-right mb-0">
                            <small class="warning text-muted">{{ $errors->first('name') }}</small>
                          </p>
                        @endif

                      </div>

                      <div class="form-group">
                        <label class="col-form-label" for="code">code</label>
                        <input class="form-control {{ $errors->has('code') ? ' is-invalid' : '' }}" id="code" type="text" name="code" value="{{ old('code')}}" placeholder="code" />
                        @if ($errors->has('code'))
                          <p class="text-right mb-0">
                            <small class="warning text-muted">{{ $errors->first('code') }}</small>
                          </p>
                        @endif
                      </div>


                      {{--<script src="{{asset('js/advanced-forms.js')}}" defer>--}}
                          {{--$('#select2-1, #select2-2, #select2-4').select2({--}}
                              {{--theme: 'bootstrap'--}}
                          {{--});--}}
                      {{--</script>--}}

                      {{-- @if($permissions->count() > 0)
                      <fieldset class="form-group">
                        <label  class="col-form-label" for="permission" >Permission</label>
                        <select class="form-control select2-multiple" name="permissions[]" id="select2-2" multiple="multiple" required >

                          @foreach($permissions as $permission)
                          <option value="{{$permission->id}}">{{$permission->name}}</option>
                          @endforeach
                        </select>
                        @if ($errors->has('permissions'))
                        <p class="text-right">
                        <small class="warning text-muted">{{ $errors->first('permissions') }}</small>
                        </p>
                        @endif --}}
                      </fieldset>

                      {{-- @else --}}

                      {{-- @endif --}}
                      <div class="form-group">
                        <button class="btn btn-primary" type="submit">Save</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- /.col-->
        </div>
        <!-- /.row-->

        <div class="animated fadeIn">
          <div class="card">
            <div class="card-header">
              <i class="fa fa-edit"></i> List merchants
              <div class="card-header-actions">

              </div>
            </div>
            <div class="card-body">
              <table class="table table-striped table-bordered datatable">
                <thead>
                <tr>
                  <th>Name</th>
                  <th>Code</th>

                  <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @if($Merchants->count() > 0)
                  @foreach($Merchants as $Merchant)
                <tr>
                  <td>{{$Merchant->name}}</td>
                  <td>
                    <p> svsvr</p>
                      {{-- {{$Merchant->code}} --}}
                    </td>

                  <td>
                    <a class="btn btn-success" href="
                    {{route('user-management.merchants.view',[\Illuminate\Support\Facades\Crypt::encrypt($Merchant->id)])}}
                    ">view
                      <i class="fa fa-search-plus"></i>
                    </a>
                    <a class="btn btn-info" href="
                    {{route('user-management.merchants.edit',[\Illuminate\Support\Facades\Crypt::encrypt($Merchant->id)])}}
                    ">edit
                      <i class="fa fa-edit"></i>
                    </a>
                    <a class="btn btn-danger" href="" onclick="deleteMerchant('')">
                     {{-- {{$Merchant->id}} --}}
delete
                      <i class="fa fa-trash-o"></i>
                    </a>

                     <form id="delete-form{{$Merchant->id}}"
                            action="
                            {{-- {{ route('user-management.merchants.delete') }} --}}
                            " method="POST" style="display: none;">
                        @csrf
                        @method('DELETE')

                        <input type="hidden" name="id"
                               value="
                               {{-- {{\Illuminate\Support\Facades\Crypt::encrypt($Merchant->id)}} --}}
                               ">
                      </form>

                  </td>
                </tr>
                  @endforeach
                @else
                  <tr>
                    <td colspan="4" class="text-center">No role  Set</td>
                  </tr>
                @endif
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>

    </div>

  </main>

@endsection
<script>
const axios = require('axios').default;

document.getElementById('InputForm').addEventListener('submit', performPostRequest);


function performPostRequest(e) {
    e.preventDefault();

//   var resultElement = document.getElementById('postResult');
  var name = document.getElementById('name').value;
  var code = document.getElementById('code').value;

//   resultElement.innerHTML = '';

  axios.post('http://localhost:8000/merchants/create', {
    name:name,
    code:code,
  })
  .then(function (response) {
      console.log('success');
    // resultElement.innerHTML = generateSuccessHTMLOutput(response);
  })
  .catch(function (error) {
      console.log('error');
    // resultElement.innerHTML = generateErrorHTMLOutput(error);
  });

}



    function deleteMerchant(key) {


        if (confirm('Are you sure, you want to delete this role?')) {
            event.preventDefault();
            document.getElementById('delete-form' + key).submit();
        } else {
            event.preventDefault();
            document.getElementById('delete-form' + key).reset();
        }




    }







</script>

resources/views/layouts/merchants/view.blade.php
@extends('layouts.app')

@section('content')
    <main class="main">
        <!-- Breadcrumb-->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">Home</li>
            <li class="breadcrumb-item">
                <a href="#">Admin</a>
            </li>
            <li class="breadcrumb-item active">Roles</li>
        </ol>
        <div class="container-fluid">
            <div class="ui-view">
                <div class="row">

                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="..." alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>

                            <p class="card-text">
                                Name : {{$role->name}}
                            </p>
                            <p class="card-text">
                                Display name : {{$role->display_name}}
                            </p>
                            <p class="card-text">
                                Description : {{$role->description}}
                            </p>
                            <p class="card-text"><b>List of permissions</b></p>
                        </div>
                        <ul class="list-group list-group-flush">
                            @foreach($role->permissions as $permission)
                                <li class="list-group-item">{{$permission->display_name}}</li>
                            @endforeach
                        </ul>
                        <div class="card-body">
                            <a href="#" class="card-link">Edit</a>
                            <a href="{{route('user-management.roles')}}" class="card-link">Back</a>
                        </div>
                    </div>
                </div>
                <!-- /.row-->
            </div>

        </div>
@endsection